### To install docker services (into .docker directory):
# docker-compose-v1.exe up -d --force-recreate --build
# docker-compose up -d --force-recreate --build

version: '2'

services:
  portainer:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: ${IMAGE}/${VER}
    command: -H unix:///var/run/docker.sock
    # restart: always
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data: