# docker compose up -d --force-recreate --build

# version: "3"

networks:
  internal:
    driver: bridge

services:
  transmission:
    container_name: "${PREFIX_PROJECT_NAME}_${SUFFIX}"
    build:
      context: /home/pi/DOCKER/transmission
      dockerfile: Dockerfile_tar
      args:
        - SO=${SO}
        - SO_VER=${SO_VER}
    user: "${PUID}:${PGID}"
    environment:
      - TZ=Europe/Madrid
      - USER=${TRANSMISSION_USER}
      - PASSWORD=${TRANSMISSION_PASSWORD}
    volumes:
      - ./config:/config
      - ./watch:/watch
      - '/media/8_TERAS/BIBLIOTECA/TORRENTS/incompletos:/media/incompletos'
      - '/media/8_TERAS/BIBLIOTECA/TORRENTS/completos:/media/completos'
    ports:
      - "${PORT_9091}:9091"
      - "${PORT_51413}:51413"
      - "${PORT_51414}:51414/udp"
    restart: unless-stopped
    networks:
      - internal
