
### In anfitrion machine ###
### To install docker services (into .docker directory):
# docker-compose-v1.exe up -d --force-recreate --build
# docker compose up -d --force-recreate --build
### To entry in php-fpm container:
# docker exec -it xx_COMPOSE_PROJECT_NAME_php_fpm_PHP_VER bash
### To entry in container with user root:
# docker exec -it -u root xx_COMPOSE_PROJECT_NAME_php_fpm_PHP_VER bash

## shor client
# docker exec -it 00_pihole-vpn_vpn /app/show-peer movilPana

# version: "3.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: ${PREFIX_PROJECT_NAME}
    # container_name: pihole
    image: ${pi_hole_IMAGE}:${pi_hole_VERSION}

    environment:
      TZ: ${TIMEZONE}
      # WEBPASSWORD: 'admin' 
      # WEBPASSWORD: 'set a secure password here or it will be random'

    # Volumes store your data between container upgrades
    volumes:
      - './etc-dnsmasq.d:/etc/dnsmasq.d/'
      - './etc-pihole:/etc/pihole/'
      # - '/media/pi/Lexar_32GB/pihole/:/var/log/pihole/'
      - '/home/pi/.config/piholeLog/:/var/log/pihole/'

    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    # network_mode: host

    dns:
      - 127.0.0.1
      - 1.1.1.1

    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

    networks:
      - ${COMPOSE_PROJECT_NAME}

networks:
  pihole:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge
