
### In anfitrion machine ###
### To install docker services (into .docker directory):
# docker-compose-v1.exe up -d --force-recreate --build
# docker-compose up -d --force-recreate --build

version: "3.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: ${PREFIX_PROJECT_NAME}_pihole
    # container_name: pihole
    image: ${pi_hole_IMAGE}:${pi_hole_VERSION}

    environment:
      TZ: ${TIMEZONE}
      # WEBPASSWORD: 'admin' 
      # WEBPASSWORD: 'set a secure password here or it will be random'

    # Volumes store your data between container upgrades
    volumes:
      - './etc-dnsmasq.d:/etc/dnsmasq.d/'
      - './etc-pihole:/etc/pihole/'
      - '/media/pi/Lexar_32GB/pihole/:/var/log/pihole/'

    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    # network_mode: host

    dns:
      - 127.0.0.1
      - 1.1.1.1

    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

    networks:
      - ${COMPOSE_PROJECT_NAME}
    depends_on:
      - wireguard


  wireguard:
    container_name: ${PREFIX_PROJECT_NAME}_vpn
    image: ${vpn_IMAGE}:${vpn_VERSION}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}

      # - SERVERURL=auto
      # - SERVERPORT=51820
      # - PEERDNS=auto
      # - PEERS=3 #change to match how many devies you want to use Wireguard on
      - PEERDNS=auto
      - PEERS=client0,client1,client2,client3,client4,client5,client6,client7,client8,client9

      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - LOG_CONFS=true #optional

    volumes:
      - ./config:/config
      - ./lib/modules:/lib/modules #do not change

    ports:
      - ${VPN_PORT}:51820/udp
    # hostname: ${COMPOSE_PROJECT_NAME}
    # network_mode: host

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

    networks:
      - ${COMPOSE_PROJECT_NAME}

    # stdin_open: true
    # tty: true

networks:
  pihole-vpn:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge