##########################################################################################################
###      _            _                                                                             _  ###
###     | |          | |                                                                           | | ###
###   __| | ___   ___| | _____ _ __ ______ ___ ___  _ __ ___  _ __   ___  ___  ___  _   _ _ __ ___ | | ###
###  / _` |/ _ \ / __| |/ / _ \ '__|______/ __/ _ \| '_ ` _ \| '_ \ / _ \/ __|/ _ \| | | | '_ ` _ \| | ###
### | (_| | (_) | (__|   <  __/ |        | (_| (_) | | | | | | |_) | (_) \__ \  __/| |_| | | | | | | | ###
###  \__,_|\___/ \___|_|\_\___|_|         \___\___/|_| |_| |_| .__/ \___/|___/\___(_)__, |_| |_| |_|_| ###
###                                                          | |                     __/ |             ###
###                                                          |_|                    |___/              ###
###                                                                                                    ###
###                                                                                                    ###
###   nginx -> default image                                                                           ###
###   php-fpm-buster -> dockerfile                                                                     ###
###   @author antonio.rodrigo@digitalvirgo.com                                                         ###
##########################################################################################################

### In anfitrion machine ###
### To install docker services (into .docker directory):
# docker-compose-v1.exe up -d --force-recreate --build
# docker-compose up -d --force-recreate --build
### To entry in php-fpm container:
# docker exec -it xx_COMPOSE_PROJECT_NAME_php_fpm_PHP_VER bash
### To entry in container with user root:
# docker exec -it -u root xx_COMPOSE_PROJECT_NAME_php_fpm_PHP_VER bash

### INIT docker-composer FILE ###
version: '3.4'

services:
  python:
    container_name: ${PREFIX_PROJECT_NAME}

    # # image
    # image: ${IMG_NAME}:${VERSION}

    ## build
    build:
      context: ./ ### dockerfiles dir
      # dockerfile: Dockerfile.${SO} ### Dockerfile
      args:
        TZ: Europe/Madrid
        IMG_NAME: ${IMG_NAME}
        VERSION: ${VERSION}

    environment:
      TZ: Europe/Madrid
      IMG_NAME: ${IMG_NAME}
      VERSION: ${VERSION}

    volumes:
      - ${WWW_PATH_EXT}:${WWW_PATH_INT}
      - ${MEDIA_PATH}:/media

    # devices:
    #   - /dev/vchiq

    ports:
      - ${PORT_FLASK}:5000

    hostname: ${COMPOSE_PROJECT_NAME}

    # user: ${PUID}:${PUID}
    working_dir: ${WWW_PATH_INT}
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t

    networks:
      - python3
      
networks:
  python3:
    name: python3
    driver: bridge
